# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
# - master

# pool:
#   vmImage: 'windows-2019'

# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'

# steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'



trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: UseDotNet@2
  displayName: Set dotnet core version
  inputs: 
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: VSBuild
  inputs:
    command: build 
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet publish -c Release -o build / 
p:PackageAsSingleFile=true
  displayName: Publish

- script: tar -a -c -C build -f Application.zip *.*
  displayName: Zip

- task: AzureWebApp@1
  displayName: 'Deploy Azure Web App'
  inputs:
    azureSubscription: 'TicketSystemNWF'
    appName: 'TicketSystemNWF'
    appType: AzureWebApp
    package: ./**/*.zip

    